version: '3'
services:
  postgres1:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: books
  
  book-service:
    build: ../book-service/
    ports:
      - "8089:8089"
    depends_on:
      - postgres1