name: deploy

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy Backend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Pull code and deploy
              uses: appleboy/ssh-action@v1.0.0
              with:
                key: ${{ secrets.SSH_KEY }}
                passphrase: ${{ secrets.PASSPHRASE }}
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                script: |
                    cd ~/RentWave
                    git pull
                    ./run.sh &
